project:
  name: "test-project"

traces:
  client:
    prefix: "client-trace-"
    count: 5
    tags: ["c-tag1", "c-tag2"]
    feedback-scores:
      c-score1: 0.5
      c-score2: 4
    metadata:
      c-md1: "val1"
      c-md2: "val2"
  
  decorator:
    prefix: "decorator-trace-"
    count: 5
    tags: ["d-tag1", "d-tag2"]
    feedback-scores:
      d-score1: 0.1
      d-score2: 7
    metadata:
      d-md1: "val1"
      d-md2: "val2"

spans:
  client:
    prefix: "client-span-"
    count: 2
    tags: ["c-span1", "c-span2"]
    feedback-scores:
      s-score1: 0.2
      s-score2: 3
    metadata:
      s-md1: "val1"
      s-md2: "val2"

  decorator:
    prefix: "decorator-span-"
    count: 2
    tags: ["d-span1", "d-span2"]
    feedback-scores:
      s-score1: 0.93
      s-score2: 2
    metadata:
      d-md1: "val1"
      d-md2: "val2"
