name: opik

services:
  mysql:
    extends:
      file: docker-compose.yaml
      service: mysql

  redis:
    extends:
      file: docker-compose.yaml
      service: redis

  clickhouse:
    extends:
      file: docker-compose.yaml
      service: clickhouse

  backend:
    build:
      context: ../../apps/opik-backend
      dockerfile: Dockerfile
      args:
        OPIK_VERSION: latest
    extends:
      file: docker-compose.yaml
      service: backend

  frontend:
    build:
      context: ../../apps/opik-frontend
      dockerfile: Dockerfile
      args:
        OPIK_VERSION: latest
    extends:
      file: docker-compose.yaml
      service: frontend

networks:
  default: