---
name: DeployPackage
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/build-package.yml
  deploy:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: download artifact
        uses: actions/download-artifact@v3
      - name: list packages
        run: find ./*package*
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: pip-package/
