# Workflow to run OpenAI tests
#
# Please read inputs to provide correct values.
#
name: Lib OpenAI Tests

on:
  workflow_call:

jobs:
  tests:
    name: OpenAI Python ${{matrix.details.python_version}}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        details:
          - python_version: "3.10"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python ${{matrix.details.python_version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.details.python_version}}

      - name: Install comet-llm
        run: pip install -e .

      - name: Install test tools
        run: |
          cd ./tests
          pip install --no-cache-dir --disable-pip-version-check -r test_requirements.txt

      - name: Install lib
        run: |
          cd ./tests
          pip install --no-cache-dir --disable-pip-version-check -r lib_integration/openai/requirements.txt

      - name: Run tests
        run: |
          cd ./tests/lib_integration/openai/
          python -m pytest  -vv -ss .