name: Unit Tests Comet LLM
on:
  pull_request:

jobs:
  UnitTests:
    name: Units_Python_${{matrix.python_version}}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print environment variables
        run: env

      - name: Print event object
        run: cat $GITHUB_EVENT_PATH

      - name: Print the PR title
        run: echo "${{ github.event.pull_request.title }}"

      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install comet-llm
        run: pip install -e .

      - name: Install test requirements
        run: |
          cd ./tests
          pip install --no-cache-dir --disable-pip-version-check -r test_requirements.txt

      - name: Running SDK Unit Tests
        run: python -m pytest --cov=src/comet_llm --cov-report=html:coverage_report_${{matrix.python_version}} -vv tests/unit/

      - name: archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report_${{matrix.python_version}}
          path: coverage_report_${{matrix.python_version}}
